#ifndef __CB_C0_H
#define __CB_C0_H

#define CONFIG_BLOCK_C0_VER_MAJOR CONFIG_BLOCK_C_VER_MAJOR
#define CONFIG_BLOCK_C0_VER_MINOR '0'
#define CONFIG_BLOCK_C0_VERSION L8_TO_LT16(CONFIG_BLOCK_C0_VER_MAJOR, CONFIG_BLOCK_C0_VER_MINOR)

#endif